### ISSUE TITLE
Setting Font for a LabeledUIComponent doesn't set size, FontStyle or FontWeight

### ISSUE THREAD

**Issue by marvingrewe** [tudo-aqua/bgw#119]

**Comment by snaujokat** [comment]
I was about to report the same thing (at least regarding font size):

![Screenshot_2021-08-04_10-00-11](https://user-images.githubusercontent.com/24932383/128144739-6e24981c-d01e-442e-b2da-56a69da157e8.png)
![Screenshot_2021-08-04_10-01-09](https://user-images.githubusercontent.com/24932383/128144768-2d254b8a-4232-4287-ae84-3091d2f544b8.png)

**Comment by dominikmaeckel** [comment]
Functionality lost in commit https://github.com/tudo-aqua/bgw/commit/db76b00171a75eb0057248ac1a5e8c67ea20456f.
