### ISSUE TITLE
Aspect ratio of initial window size

### ISSUE THREAD

**Issue by snaujokat** [tudo-aqua/bgw#120]
The initial window size should honor the aspect ratio of the initial scene. Currently, the application window is opened as 16:9, even when I have a square scene.

If the size of the scene is not known during opening the window, BoardGameApplication should have a parameter for initial aspect ratio (not size, as this should be determined dynamically, based on the available screen resolution)

**Comment by fabiankluempers** [comment]
How should we restrict the maximum dimensions of the window? I guess HD or full HD should be the maximum size of the window on startup?

**Comment by snaujokat** [comment]
Is it not possible to retrieve the desktop resolution?

**Comment by fabiankluempers** [comment]
It is possible. So the window dimensions should be maximized while preserving the ratio of the scene? What about instances where we have a menuScene and a gameScene with different ratios?

**Comment by snaujokat** [comment]
Instead of "maximized", I'd go for ~70% of max size, just like it is now with the 720p window size (given one has a full HD display)

Good point with menuScene vs gameScene, though. I think we should favor the aspect ratio of the gameScene. Maybe later we can think about explicitly adding a parameter `aspectRatio = AspectRatio(16,9)`  to the BoardGameApplication.
