### ISSUE TITLE
GridPane does not show

### ISSUE THREAD

**Issue by fabiankemper** [tudo-aqua/bgw#153]
**Describe the bug**
The GridPane does not show itself and its content if added to scene.

**Minimal Code example**
```kotlin

class GameScene(): BoardGameScene() {
  init {
    val grid = GridPane<Button>(0, 0, 2, 2)
    grid[0, 0] = Button(text="Hello")
    addComponents(grid)
  }
}
```

**Expected behavior**
Grid is visible in scene. 

 - OS: Linux, MacOS
 - Java version 11, 16

**Comment by dominikmaeckel** [comment]
Fixed in ca1391b.
