### ISSUE TITLE
Weird Animation Cancel for onMouseEntered and onMouseExited

### ISSUE THREAD

**Issue by heaterscar** [tudo-aqua/bgw#163]
**Describe the bug**
A predefined movement animation gets canceled when the Mouse is moving exiting the animated component while the entering animation is playing. This leads so far that the components position is getting out of the predefined bounds for the movement animation. For example a card which is movement animated the following:

`

        card.onMouseEntered = {
                playAnimation(
                    MovementAnimation(
                        componentView = card,
                        byX = 0,
                        byY = -20,
                        duration = 200
                    ).apply {
                        onFinished = {
                            card.posY -= 20
                        }
                    }
                )
        }

        card.onMouseExited = {
            playAnimation(
                MovementAnimation(
                    componentView = card,
                    byX = 0,
                    byY = 20,
                    duration = 200
                ).apply {
                    onFinished = {
                        card.posY += 20
                    }
                }
            )
        }

`

You might think this happens because of the low animation time, but i tested it with even slower animation times up to 5sec. Everytime the mouse wiggles over the card a new asynchronous coroutines for the animation gets fired up. So this might just be a race condition issue.

**To Reproduce**
1. Define onMouseEntered and onMouseExited as shown above
2. Move the Mouse over the card in on go from left to right
3. Move the Mouse back over the card again in one go, but now from right to left
4. Repeat steps two and three very quickly

**Expected behavior**
Card should move up and down only in a range of [0,20] and not outside of these bounds

**Screenshots**
Normal Case (Expected behavior)
![Normal Case](https://user-images.githubusercontent.com/45982681/131641825-84302c48-0383-4e96-ac58-d0c18603abc0.gif)

Animation Cancel Case
![Animation Cancel](https://user-images.githubusercontent.com/45982681/131641640-76019eb3-393c-4fcb-abba-ea2801f0f356.gif)

Moving out of Bounds Case
![Moving out of Bounds](https://user-images.githubusercontent.com/45982681/131641864-0703662b-3bf3-4c75-9383-ce89432860c5.gif)

Please complete the following information):
 - OS: Windows 10 Home - Version 20H2 - Build 19042.1165
 - Java Version "11.0.8" 2020-07-14 LTS
   Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
   Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

**Additional context**
Card hover Effect is used for animating a players hand cards

**Comment by dominikmaeckel** [comment]
The issue is already known.
If you set onMouseExited to move the card -20px, the animation will play from the current position, which may not be +20px because the onMouseEntered has not finished yet.

Suggestions for how to avoid this are welcome.
The issue is, that on animation start we don't know which other animation (e.g. onMouseEntered) to cancel. This is not a BGW bug, but a fundamental problem in using movement according to mouse position. Another effect occurs when the movement moves the card such that the mouse leaves it.
