### ISSUE TITLE
Warning from java-fx when using ColorVisual with alpha component 

### ISSUE THREAD

**Issue by colinkolbe** [tudo-aqua/bgw#164]
**Describe the bug**
"WARNUNG: CSS Error parsing '*{-fx-background-color: #10101;}: Invalid color specification while parsing '-fx-background-color' at [1,24]" 
When using a ColorVisual with a alpha component close to zero. 
The other color components seems to have no influence on the warning. 

**To Reproduce**
1. Create, for example, "private val transparentVisual = ColorVisual(1, 1, 1, 1)" 
2. Add it to a Label or Button property "visual = transparentVisual"
3. Use it in a Scene 

**Expected behavior**
No warning message.

**System info**
 - Windows 10
 - Java version: AdoptOpenJDK 11.0.8

**Additional context**
Info: Program functionality is not impaired, just a warning message

**Comment by dominikmaeckel** [comment]
Integer.toHex seems to trim the leading 0.
Will be fixed in v0.3.

Current workaround is to use the opacity property.
