### ISSUE TITLE
manual setting of column width and row height of GridPane does not work

### ISSUE THREAD

**Issue by Thomas-01K** [tudo-aqua/bgw#176]
**Describe the bug**
Doc describes that if you set the row height and column width with setRowHeight() and setColumnWidth, it also sets the width and height permanent to this size, but it does not work.

**To Reproduce**
1. Create GridPane, set visual = ColorVisual.ORANGE
2. Set height and width with setRowHeight(), setColumnWidth()
3. Add GridPane to gui
4. Run application and see "nothing":)

**Expected behavior**
You should see a field with an organge background.

Please complete the following information):
Windows 10
 - Java version: "11.0.12"

**Comment by dominikmaeckel** [comment]
Thank you for the bug report!
Setting fixed row and colum sizes works as soon as the grid contains at least one element in this column/row. In other words: Empty columns and empty rows get trimmed atm.
I agree that this leads to unexpected behavior. Will be changed in v0.4

I recomment putting an area into each cell and then either setting the area's size or the colum/row size to the expected dimensions.
