### ISSUE TITLE
MovementAnimation#toComponentView animates to wrong position

### ISSUE THREAD

**Issue by Chasethechicken** [tudo-aqua/bgw#188]
**Describe the bug**
When trying to animate from an Area to a GridPane, tokens sometimes miss their target and snap to their target when adding them to the GridPane in onFinished.

**To Reproduce**
I have provided a minimal demonstration at https://github.com/Chasethechicken/bgw/tree/animate-to-component/bugexample
1. Start the application.
2. Click on the blue token.
3. It should animate to the top left of the GridPane.
4. Instead, it misses and snaps to the correct spot.

**Expected behavior**
The token should animate to the right location without snapping there.

**Please complete the following information**
 - OS: Fedora 34
 - Java version: openJDK 16

**Additional context**
- This setup is slightly different from #173, as the target is the GridPane itself and not an Area contained in it.
  I have verified #173 to be fixed.
- This was tested using `dev`, commit `e26b2a89`

**Comment by dominikmaeckel** [comment]
For me the behavior works as expected as the gird is *layoutFromCenter*.
This means the Token will animate its top-left corner to the grids center.

I see no use in using toComponentView on GridViews as it does not specify which cell to animate to.
Animating it to cell [0,0] i.e. top-left would be an option, but I see no real use for that.
Please further specify what you would expect.

**Comment by Chasethechicken** [comment]
But `toComponentViewPosition` is not the GridPane itself, but rather a TokenView contained in a GridPane.
Thats why I would expect the animation to target that TokenView.

When changing the the x and y parameters in line 33 of my example, 
for example to 1 and 1, the animation does target a different TokenView, but is still offset.

**Comment by dominikmaeckel** [comment]
Sorry, I missed that line 65.
Bug has already been fixed in bcf19d968b6157e95562d838953bdefafea859fd.
