### ISSUE TITLE
Position properties are wrong after MovementAnimation

### ISSUE THREAD

**Issue by Chasethechicken** [tudo-aqua/bgw#192]
**Describe the bug**
After animating a component using MovementAnimation, the `posX` and `posY` properties are wrong.

**To Reproduce**
There is a demonstration available here: https://github.com/Chasethechicken/bgw/tree/animation-positions/bugexample
1. Start the application
2. The terminal will output expected and actual positions.
   These are all as I would expect them to be.
3. Click on the blue token to start an animation.
4. The terminal will once again contain coordinates.
   This time, the positions will be the same as before the animation.
5. Thus, trying to reset the position to `0, 0` will do nothing.

**Expected behavior**
I'd either expect the `posX` and `posY` properties to contain the current position after animating the component, 
or the component should snap back to the position contained in these properties.

**Please complete the following information**
 - OS: Fedora 34
 - Java version: openJDK 16

**Additional context**
- Demo application output:
```
Expected: 0 / 0  
0.0  
0.0  
Expected: 50 / 50  
50.0  
50.0  
Expected: 0 / 0  
0.0  
0.0  
Expected: 200 / 200  
0.0  
0.0  
Expected: 0 / 0  
0.0  
0.0

**Comment by dominikmaeckel** [comment]
As mentioned in the docs (https://tudo-aqua.github.io/bgw/concepts/animations/Animations.html#movementanimation) the position does not get updated after animation as this may cause rendering issues for the container the element is technically still contained in. The user has to either set the new postion in onFinished or the element will snap back upon next refresh.
This behaviour is analogue to the default behaviour of javaFX or other GUI frameworks. An animation is considered as a temporary translation of an object, not as a movement.

**Comment by Chasethechicken** [comment]
But as the element is only rerendered, if the position is changed, the position can be updated to be the new position or any other position just fine.
But if the snapping back behaviour was actually desired, it is not achievable by just setting the position of the element to the old position, as this does not trigger a rerendering.

**Comment by dominikmaeckel** [comment]
You may use notifyUnchanged() on the properties which fires onChanged handlers.
