### ISSUE TITLE
Position of nested GridPane changes when adding components

### ISSUE THREAD

**Issue by fabiankemper** [tudo-aqua/bgw#221]
**Describe the bug**
When adding components to a nested GridPane, its position in the parent GridPane is changed.

**To Reproduce**
Example code with a workaround added. 
[NewGameScene.kt](https://github.com/tudo-aqua/bgw/files/8116010/NewGameScene.txt)

**Expected behavior**
The position of the nested GridPane should not change to (0, 0).

**Comment by dominikmaeckel** [comment]
This may be related to #161.

**Comment by dominikmaeckel** [comment]
Fix may be reviewed in #237
