### ISSUE TITLE
`CardView.showCardSide(...)` broken after finished `FlipAnimation`

### ISSUE THREAD

**Issue by MonsterDruide1** [tudo-aqua/bgw#320]
**Describe the bug**
After a finished flip animation, setting a `CardView`s side does not have any effect until the CardView is completely reset by re-adding it to the surrounding container.

**To Reproduce**
Look at the following example scene:
```kotlin
import tools.aqua.bgw.animation.FlipAnimation
import tools.aqua.bgw.components.gamecomponentviews.CardView
import tools.aqua.bgw.components.uicomponents.Button
import tools.aqua.bgw.core.BoardGameScene
import tools.aqua.bgw.core.DEFAULT_ANIMATION_DURATION
import tools.aqua.bgw.visual.ColorVisual

class FlipExampleClass : BoardGameScene() {

    private val frontFace = ColorVisual.GREEN
    private val backFace = ColorVisual.RED
    private val card = CardView(width/2, height/2, front=frontFace, back=backFace)
    private val resetButton = Button(200, 200, text="RESET").apply {
        onMouseClicked = { reset() }
    }
    private val flipButton = Button(200, 400, text="FLIP").apply {
        onMouseClicked = { playAnimation(FlipAnimation(card, frontFace, backFace, DEFAULT_ANIMATION_DURATION*3)) }
    }
    private val frontButton = Button(200, 600, text="FRONT").apply {
        onMouseClicked = { card.showFront() }
    }
    private val backButton = Button(200, 800, text="BACK").apply {
        onMouseClicked = { card.showBack() }
    }


    init {
        card.showFront()
        addComponents(card, resetButton, flipButton, frontButton, backButton)
    }

    private fun reset() {
        card.removeFromParent()
        addComponents(card)
    }

}
```

**Expected behavior**
After clicking on `FLIP` and the animation finished, using the `BACK` and `FRONT` button should have an effect on the visible side of the card. However, they don't, until the card is re-added to the scene using the `RESET` button.

**Screenshots**
See the code above.

Please complete the following information:
 - OS: Windows 10
 - Java version Oracle JDK 16

**Additional context**
A few more actions on `CardView`s have this broken behaviour, as discussed in the SoPra-Help channel earlier today. However, this is the easiest one to reproduce.

**Comment by dominikmaeckel** [comment]
Seems to work fine on current snapshot. Might have been fixed in 81e1a5ac6e0724cae7ad781fdf56410bbcb3fb5f.

The example works fine by changing 
````kotlin
onMouseClicked = { playAnimation(FlipAnimation(card, frontFace, backFace, DEFAULT_ANIMATION_DURATION*3))
````

to

````kotlin
onMouseClicked = {
  val fromVisual = if (card.currentSide == CardView.CardSide.BACK) card.backVisual else card.frontVisual
  val toVisual = if (card.currentSide == CardView.CardSide.BACK) card.frontVisual else card.backVisual
  playAnimation(FlipAnimation(card, fromVisual, toVisual, 1000))
}
````

Please check again against the current snapshot or close the issue as fixed.

**Comment by MonsterDruide1** [comment]
I can't compile the latest version, due to the following error:
```
e: ...\bgw\bgw-gui\src\main\kotlin\tools\aqua\bgw\builder\AnimationBuilder.kt: (41, 7): 'when' expression must be exhaustive, add necessary 'else' branch
```

Should this go into a separate issue?

**Comment by MonsterDruide1** [comment]
I explicitly did not do the provided change to give a minimal example of broken behaviour. The animation itself works fine, and I know that it intends to jump at the start of the animation. The important thing to notice here is that the `BACK` and `FRONT` buttons are broken after the animation finished playing, until the CardView is reset.

**Comment by dominikmaeckel** [comment]
``BACK`` and ``FRONT`` button work fine in my tests.

``'when' expression must be exhaustive`` error is caused by a known bug in the kotlin plugin in intelliJ. Gradle clean and recompile should fix the issue.

**Comment by MonsterDruide1** [comment]
Okay, that fixed the compile - and some commit in the meantime fixed the issue, so this is resolved.
