### ISSUE TITLE
Auto resizing on startup unstable on different devices

### ISSUE THREAD

**Issue by dominikmaeckel** [tudo-aqua/bgw#60]
Resizing of window is sometimes required after startup on different devices

**Comment by dominikmaeckel** [comment]
Test again now that resizing is delayed.

**Comment by fabiankluempers** [comment]
This is what it looks like after startup on my win10 machine, 1440p resolution. After resizing the window everything is centered as it should be. But everytime a scene is shown or hidden it goes back into the zoomed state (as seen in the screenshot).
![image](https://user-images.githubusercontent.com/54634644/125449056-2f1a7e49-cce1-43b6-b826-4b7cd50802cf.png)

**Comment by dominikmaeckel** [comment]
Issue happens when dpi scaling is set != 100%

**Comment by fabiankluempers** [comment]
The workaround is not very elegant and should be changed if we want to keep javafx.

**Comment by snaujokat** [comment]
@fabiankluempers the commit diff is not very legible. What is the workaround? For me, window sizing seems to work now.

**Comment by dominikmaeckel** [comment]
@snaujokat The workaround is to actively change the window size by one pixel every time the scene gets updated (alternatingly +/- 1px) which forces JavaFX to re-render the window. From outside there is no solution to wait for the renderer to finish first rendering before changing the window size. This seems to be a JavaFX bug as the calculated window size is not considering dpi scaling before first rendering.
